pathRow1;
        // pathCol1;
        // pathRow2;
        // pathCol2;
        // pathRow3;
        // pathCol3;
        // pathRow4;
        // pathCol4;
        // pathRow5;
        // pathCol5;
        // pathRow6;
        // pathCol6;
        // pathRow7;
        // pathCol7;